### ISSUE TITLE
Provide a method to extract state variables from mod file

### ISSUE THREAD

**Issue by brunomaga** [BlueBrain/mod2c#27]
Hi Michael @nrnhines 

I'm trying to extract the extract the state variables and their derivatives from the c-generated mod file. 

Take as an example the following code extracted from `KdShu2007.cpp`:

```
[...]
#define ek _p[1*_STRIDE]
#define ik _p[2*_STRIDE]
#define m _p[3*_STRIDE]
#define h _p[4*_STRIDE]
#define Dm _p[5*_STRIDE]
#define Dh _p[6*_STRIDE]
#define _v_unused _p[7*_STRIDE]
#define _g_unused _p[8*_STRIDE]
[...]
```

So far there exists a method to extract only the ode count. Ideally I'd also need a method that extracts the offsets of the `m`, `h`, `dm` and `dh`.  Here is a suggestion of how to extract the count and offsets of each variable:

```
 void _nrn_ode_state_offsets__KdShu2007(short * count, short** var_offsets, short ** dv_offsets)
 {
     *count = 2;
     (*var_offsets) = (short*) malloc(sizeof(short)* *count);
     (*dv_offsets) = (short*) malloc(sizeof(short)* *count);
     (*var_offsets)[0] = 3;
     (*var_offsets)[1] = 4;
     (*dv_offsets)[0] = 5;
     (*dv_offsets)[1] = 6;
 }
```

or if it's guaranteed that state and d-vars are *always* sequentially placed in the `_p` array, simply provide the offsets of the first element:

```
 void _nrn_ode_state_offsets__KdShu2007(short * count, short* var_offsets, short * dv_offsets)
 {
     *count = 2;
     *var_offsets = 3;
     *dv_offsets = 5;
 }
```

This would be useful for CVODE(S) -based computation. So far I'm writing these functions by hand on each c-generated mod file. However, this is not a good solution at long term.

Thank you

**Comment by nrnhines** [comment]
Hi Bruno,
I'm looking at the hh.c generated by mod2c and see that a some of the cvode
stuff is still there (_ode_spec1 for y'=f(y) and _ode_matsol for approxiate
jacobian) but a lot get #if 0 away in mod2c so that things relevant to
hoc_register_cvode(_mechtype, _ode_count, _ode_map, _ode_spec, _ode_matsol);
hoc_register_tolerance(_mechtype, _hoc_state_tol, &_atollist);
are missing.

Anyway, the information you are looking for is part of the
int* _slist1;
int* _dlist1;
that are filled in the static void _initlists(){
and give the offsets for state and dstate.

In the classical NEURON world, this information was also encoded in
static const char *_mechanism[] = {
which defined the layout of the _p array in terms of PARAMETER, ASSIGNED,
STATE

Cheers,
Michael

**Comment by brunomaga** [comment]
Thank you Michael @nrnhines , I will have a look ASAP and close the ticket if that solves it.
Cheers, Bruno

**Comment by brunomaga** [comment]
Hi Michael @nrnhines 
I double-checked the code.
Indeed `_slist` and `_dlist` provide the offsets for state vars and D-state vars. Populated when `_<mech-name>_reg()` functions calls `_initlists()`.
I believe this solves the issue.
Thank you vm

**Comment by brunomaga** [comment]
Hi Michael @nrnhines .
After checking thoroughly, the `_slist1` and `_dlist1` are private in the context of the mod file. Also, no variable is available to express how many state vars exist, i.e. the length of the 2 arrays.
To make those changes, I implemented the following on each mechanism:
```
void nrn_ode_state_vars(int * var_count, int ** var_offsets, int ** dv_offsets) {
  *var_count = _cvode_neq;
  *var_offsets = _slist1;
  *dv_offsets = _dlist1;
}
```
and added a new variable `_cvode_neq`.

The diff of the implementation is the following, and I'll leave it here for future implementation if possible. 
It's the commit `5dbd3c483dfa0029a37c4c39a4557f86ba73cf57` in the branch `brunos_use_case`, if you need to `git cherrypick`. 

```
--- a/src/mod2c_core/deriv.c
+++ b/src/mod2c_core/deriv.c
@@ -635,11 +635,13 @@ if (s->subtype & ARRAY) { int dim = s->araydim;
 
          "\n#define _slist%d _slist%d%s\n"
          "int* _slist%d;\n"
+         "#define _cvode_neq _cvode_neq_%s\n"
+         "int _cvode_neq;\n"
          "#pragma acc declare create(_slist%d)\n"
          "\n#define _dlist%d _dlist%d%s\n"
          "int* _dlist%d;\n"
          "#pragma acc declare create(_dlist%d)\n"
-         , numlist, numlist, suffix, numlist, numlist
+         , numlist, numlist, suffix, numlist, suffix, numlist
          , numlist, numlist, suffix, numlist, numlist
          );
                Linsertstr(procfunc, buf);
@@ -687,6 +689,14 @@ if (s->subtype & ARRAY) { int dim = s->araydim;
        vectorize_scan_for_func(qq, procfunc);
   }
 
+        Lappendstr(procfunc,
+                       "\n\
+void nrn_ode_state_vars(int * var_count, int ** var_offsets, int ** dv_offsets) {\n\
+  *var_count = _cvode_neq;\n\
+  *var_offsets = _slist1;\n\
+  *dv_offsets = _dlist1;\n\
+}\n");
+
        Lappendstr(procfunc, "/*END CVODE*/\n");
```
and 
```
--- a/src/mod2c_core/nocpout.c
+++ b/src/mod2c_core/nocpout.c
@@ -445,12 +445,14 @@ fprintf(stderr, "Notice: ARTIFICIAL_CELL models that would require thread specif
 #define nrn_state _nrn_state_%s\n\
 #define initmodel initmodel_%s\n\
 #define _net_receive _net_receive_%s\n\
+#define _net_receive2 _net_receive2_%s\n\
 #define nrn_state_launcher nrn_state%s_launcher\n\
 #define nrn_cur_launcher nrn_cur%s_launcher\n\
 #define nrn_jacob_launcher nrn_jacob%s_launcher\n\
 #define _ode_matsol1 _nrn_ode_matsol1_%s\n\
 #define _ode_spec1 _nrn_ode_spec1_%s\n\
-", suffix, suffix, suffix, suffix, suffix, suffix, suffix, suffix, suffix, suffix, suffix, suffix, suffix);
+#define nrn_ode_state_vars _nrn_ode_state_vars_%s\n\
+", suffix, suffix, suffix, suffix, suffix, suffix, suffix, suffix, suffix, suffix, suffix, suffix, suffix, suffix, suffix);
        Lappendstr(defs_list, buf);
 
        if (net_receive_buffering_) {
@@ -2777,11 +2779,12 @@ static void _ode_map(int _ieq, double** _pv, double** _pvdot, double* _pp, Datum
                sprintf(buf, "\
        int _i; _p = _pp; _ppvar = _ppd;\n\
        _cvode_ieq = _ieq;\n\
+       _cvode_neq = %d;\n\
        for (_i=0; _i < %d; ++_i) {\n\
                _pv[_i] = _pp + _slist%d[_i];  _pvdot[_i] = _pp + _dlist%d[_i];\n\
                _cvode_abstol(_atollist, _atol, _i);\n\
        }\n",
-                       cvode_neq_, cvode_num_, cvode_num_);
+                       cvode_neq_, cvode_neq_, cvode_num_, cvode_num_);
                Lappendstr(procfunc, buf);
 /* need to take care of case where a state is an ion concentration. Replace
 the _pp pointer with a pointer to the actual ion model's concentration */
@@ -3031,6 +3034,8 @@ sprintf(buf, "\
        }
 
        sprintf(buf, "\
+\nvoid _net_receive2 (NrnThread * _nt, Memb_list* _ml, int _iml, int _weight_index, double _lflag, double _nrb_t);\
+\n\
 \nstatic void _net_receive (Point_process* _pnt, int _weight_index, double _lflag) {\
```

I'll reopen the ticket and leave it up to you to decide whether this is an intended feature or not, and close the ticket accordingly.
Thank you

**Comment by nrnhines** [comment]
This is ok but I would prefer not introducing the variable _cvode_neq.  or indeed, changing deriv.c at all.
All the information needed to generate nrn_ode_state_vars_%s is available in nocpout.c. eg.see the
cvode_emit_interface() function.  Notice how there is never an explicit _slist1 emitted but _slist%d. The
relevant nocpout.c variables are cvode_neq_ and cvode_num_. Also it is not clear to me why
_net_receive is changed to _net_receive2. Is there perhaps a more mnemonic name to distinquish it
from _net_receive

**Comment by brunomaga** [comment]
`net_receive2` is an artefact of some side development for another ticket (I now changed that comment to remove those line)
Yes, your suggestions is good and I am ok with the variables and notations you mentioned being as you propose, as long as there's a method (similar to the `void nrn_ode_state_vars(int * var_count, int ** var_offsets, int ** dv_offsets)`) to extract them. I can merge my changes to the `master` branch or let you implement it and I'll adapt my code accordingly.
Thank you very much for your support.

**Comment by nrnhines** [comment]
Please make the changes and I will review.

**Comment by brunomaga** [comment]
I just double checked: it will take a while to merge because the changes are spread across several commits that add also other functionalities. I'll handle it asap.

**Comment by pramodk** [comment]
Not relevant anymore, all new development happens in https://github.com/BlueBrain/nmodl
