### ISSUE TITLE
Allow call of net_receive functions and use of its function pointers without coreneuron-specific global variables

### ISSUE THREAD

**Issue by brunomaga** [BlueBrain/mod2c#3]
Hi Michael @nrnhines 

At the moment a call to a given `net_receive` function requires one to declare the global `nrn_threads` variable and pass `Point_Process` type variable that includes coreneuron-specific info such as `NrnThread id`.

Ideally one should be able to call a `net_receive` function by only passing the minimum parameters required and without any requirement of neuron-specific global variables i.e.:
```
void net_receive (NrnThread*, Memb_list *ml, int _iml, int _weight_index, double _lflag)
```

Also, one cannot use `net_receive` functions unless it registers them with the `reg_mod` function that also includes information from global variables. To be able to extract those function pointers from an `extern void net_receive (...)` file, the `static` should be removed from the `net_receive` declaration.

As an example, I corrected two C-generated MOD files with the corrections that handle both issues:

[ProbAMPANMDA_EMS.c.txt](https://github.com/BlueBrain/mod2c/files/790162/ProbAMPANMDA_EMS.c.txt)
[ProbGABAAB_EMS.c.txt](https://github.com/BlueBrain/mod2c/files/790161/ProbGABAAB_EMS.c.txt)

For back-compatibility, the calls I proposed are done via the `net_receive2` function, while `net_receive` functions keep the same header as before.

With this ticket I'd like those changes to be propagated to the mod2c code either with the logic I propose or some other solution you may find more appropriate.

Thank you in advance

**Comment by nrnhines** [comment]
Hi Bruno,
I don't completely understand the issue, although it will be a simple matter
for me to modify mod2c_core to do what you want.
The git reposititories are suffering from a bit of a problem in that gerrit changes
are not easy to merge with the github versions at present. I believe this is
because gerrit changes all the commit hashes (you can discuss with Pramod).
Right now I'd like to finish my grant proposal before fully dealing with the
proposed change or equivalent variant and the git repository issues.
I'll be at campus biotech after march 1.
Can we discuss then? 
Cheers,
Michael

**Comment by brunomaga** [comment]
Hi Michael.
Yes, that is good.
We can discuss it on March 1st.
Thank you for the quick reply!
Cheers,
Bruno

**Comment by brunomaga** [comment]
Note: I tried to manually make it work for the time being, won't be so easy due to calls to `net_send` or `artcell_*` in `netcvode.cpp` which depend on the global variables. These are the cases of eg `pattern.mod`, `netstim.mod` and `netstim_inhpoisson.mod`: they call functions of the `SelfEvent` class that depends on the global variables that define the queue of events etc etc.

**Comment by pramodk** [comment]
@brunomaga : I think this can be closed now?

**Comment by brunomaga** [comment]
No. At the moment,  I'm still using the `net_receive2` (also declared in `membfunc.h` as `pnt_receive2` type) function to overcome the limitations of `net_receive` being Coreneuron specific. Did you look into this?

**Comment by brunomaga** [comment]
membfunc.h:
```
typedef void (*pnt_receive_t)(Point_process*, int, double);
typedef void (*pnt_receive2_t)(struct NrnThread * _nt, Memb_list* _ml, int _iml, int _weight_index, double _lflag);
```

Mechanisms functions are then:
```  
pnt_receive2_t pnt_receive_;
pnt_receive2_t pnt_receive_init_;
```

**Comment by pramodk** [comment]
Not relevant anymore, all new development happens in https://github.com/BlueBrain/nmodl
