### ISSUE TITLE
Issue when linking with `extern` and `static` function declarations

### ISSUE THREAD

**Issue by brunomaga** [BlueBrain/mod2c#30]
Hi Michael Hines @nrnhines
I'm having an issue with linking when compiling coreneuron against the latest mod2c generated C files. 

Environment:
- mod2c master branch (`df45c70c727861f0ee68fefbe986e5218de4d5d4`)
- coreneuron master branch (`ba64cfac3c719777ec4ac9553df0beee3e697616`).

Compilation of coreneuron:
- `cmake .. -DCMAKE_BUILD_TYPE=Debug  -DADDITIONAL_MECHPATH=$NEURODAMUS_LIB_PATH          -DADDITIONAL_MECHS=$ADDITIONAL_MECHS_PATH  -DDISABLE_NRN_TIMEOUT=ON  -DUNIT_TESTS=OFF  -DFUNCTIONAL_TESTS=OFF`
- compiler `nix/mvapich2-rdma/2.2` with `nix/gcc/6.4.0`, on machine `bbpv1.epfl.ch`

The following error occurs during linking:
```
[100%] Linking CXX executable ../bin/coreneuron_exec
../coreneuron/libcoreneuron.so.1.0.1: undefined reference to `coreneuron::_net_receive__VecStim(coreneuron::Point_process*, int, double)'
../coreneuron/libcoreneuron.so.1.0.1: undefined reference to `coreneuron::_net_receive__InhPoissonStim(coreneuron::Point_process*, int, double)'
../coreneuron/libcoreneuron.so.1.0.1: undefined reference to `coreneuron::_net_receive__ExpSyn(coreneuron::Point_process*, int, double)'
../coreneuron/libcoreneuron.so.1.0.1: undefined reference to `coreneuron::_net_receive__BinReportHelper(coreneuron::Point_process*, int, double)'
../coreneuron/libcoreneuron.so.1.0.1: undefined reference to `coreneuron::_net_receive__ProbGABAAB_EMS(coreneuron::Point_process*, int, double)'
../coreneuron/libcoreneuron.so.1.0.1: undefined reference to `coreneuron::_net_receive__GluSynapse(coreneuron::Point_process*, int, double)'
../coreneuron/libcoreneuron.so.1.0.1: undefined reference to `coreneuron::_net_receive__Exp2Syn(coreneuron::Point_process*, int, double)'
../coreneuron/libcoreneuron.so.1.0.1: undefined reference to `coreneuron::_net_receive__ProbAMPANMDA_EMS(coreneuron::Point_process*, int, double)'
../coreneuron/libcoreneuron.so.1.0.1: undefined reference to `coreneuron::_net_receive__PatternStim(coreneuron::Point_process*, int, double)'
```
It's due to using `extern` definition of `static` functions. `extern` expects an external definition, yet `static` defines the method to belong only to the compilation unit it's defined on.

I had similar issues before, see issues https://github.com/BlueBrain/mod2c/issues/3 and https://github.com/BlueBrain/mod2c/issues/25 .

I pushed a fix to the branch `external_static_link_fix` and asked for a pull request.
Leave it up to you on how to proceed. Thank you.

**Comment by nrnhines** [comment]
I'm not familiar with all the implications. Can we get @pramodk to weigh in on this.

**Comment by pramodk** [comment]
@brunomaga  : I have fixed the tests and its ok to merge #31. That expose net_receieve/net_init kernels (similar to nrn_state). 

But, I couldn't reproduce the issue you mentioned on BB5 with:

```
module load nix/cmake nix/mvapich2-rdma/2.2 nix/gcc/6.4.0
 git clone --recursive http://github.com/BlueBrain/coreneuron
 cd coreneuron/
 mkdir build && cd build/
 cmake ..
 make -j
```

**Comment by brunomaga** [comment]
The fix worked. Thank you. I'll close the ticket.

**Comment by pramodk** [comment]
@brunomaga  : ok, thanks.

Were you able to re-produce the issue? I am asking because coreneuron is [still using the old version](https://github.com/BlueBrain/CoreNeuron/tree/master/external) (i.e. before the commit on #31). And hence I wonder if there was any issue or if this was caused by your local modifications.
